repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: fix-byte-order-marker
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: mixed-line-ending

ci:
    autoupdate_schedule: weekly
